FROM python:3.11.0

RUN apt-get update

COPY . cargo-finder/

WORKDIR cargo-finder

ENV PYTHONPATH=/cargo-finder:/cargo-finder/src

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

#RUN python -m src.db_start

#CMD ["src.main"]

CMD ["bash", "-c", "while true; do sleep 1; done"]
