version: "3.9"

services:
  db:
    image: postgres:14.6-alpine
    container_name: cargo_finder-postgresql
    env_file:
      - .env
    environment:
      - POSTGRES_URL=${DB_URL}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=cargo_finder
    volumes:
      - ./pddata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile-fastapi
    container_name: cargo_finder-fastapi
    tty: false
    restart: on-failure
    volumes:
      - .:/cargo-finder
    ports:
      - "${SERVER_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
